from __future__ import annotations

import json
import logging
from typing import Any

from databricks.sdk import WorkspaceClient
from databricks.sdk.service.vectorsearch import RerankerConfig, RerankerConfigRerankerParameters

from .base import BaseNode, NodeConfigField, resolve_state
from . import register

logger = logging.getLogger(__name__)


@register
class VectorSearchNode(BaseNode):
    @property
    def node_type(self) -> str:
        return "vector_search"

    @property
    def display_name(self) -> str:
        return "Vector Search"

    @property
    def description(self) -> str:
        return "Query a Databricks Vector Search index for relevant documents."

    @property
    def category(self) -> str:
        return "retrieval"

    @property
    def icon(self) -> str:
        return "search"

    @property
    def color(self) -> str:
        return "#06b6d4"

    @property
    def config_fields(self) -> list[NodeConfigField]:
        return [
            NodeConfigField(
                name="query_from",
                label="Query from",
                field_type="state_variable",
                default="input",
            ),
            NodeConfigField(
                name="index_name",
                label="Vector Search Index",
                placeholder="catalog.schema.my_vs_index",
            ),
            NodeConfigField(
                name="endpoint_name",
                label="VS Endpoint Name",
                placeholder="my-vs-endpoint",
            ),
            NodeConfigField(
                name="columns",
                label="Columns to Return",
                placeholder="content, source",
                help_text="Comma-separated list of columns to return from the index.",
            ),
            NodeConfigField(
                name="num_results",
                label="Number of Results",
                field_type="number",
                required=False,
                default=3,
            ),
            NodeConfigField(
                name="score_threshold",
                label="Score Threshold",
                field_type="number",
                required=False,
                help_text="Minimum similarity score (0-1). If set, only results above this threshold are returned.",
            ),
            NodeConfigField(
                name="filters_from",
                label="Filters from",
                field_type="state_variable",
                required=False,
                help_text='State variable containing a filters JSON string, typically generated by an upstream LLM node. Exact match: {"department": "cardiology"}. Comparisons: {"year >=": 2020}. Multiple values: {"col": ["a", "b"]}. Do NOT use "=" operator — exact match is the default.',
            ),
            NodeConfigField(
                name="enable_reranker",
                label="Enable Reranker",
                field_type="select",
                required=False,
                options=["true", "false"],
                default="true",
                help_text="Re-score results by relevance using the Databricks reranker. Note that this may incur additional latency.",
            ),
            NodeConfigField(
                name="columns_to_rerank",
                label="Columns to Rerank",
                required=False,
                placeholder="content, source",
                help_text="Order matters — the reranker processes columns left-to-right and only considers the first 2000 characters total. Put the most important column first.",
            ),
        ]

    def execute(self, state: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
        writes_to = config.get("_writes_to", "")
        query = resolve_state(state, config.get("query_from", "input"))
        num_results = int(config.get("num_results", 3))
        index_name = config.get("index_name", "")
        endpoint_name = config.get("endpoint_name", "")
        columns_raw = config.get("columns", "")

        if not index_name:
            return {
                writes_to: "Error: no Vector Search index configured.",
                "messages": [{"role": "system", "content": "Vector Search: missing index_name.", "node": "vector_search"}],
            }
        if not endpoint_name:
            return {
                writes_to: "Error: no Vector Search endpoint configured.",
                "messages": [{"role": "system", "content": "Vector Search: missing endpoint_name.", "node": "vector_search"}],
            }
        if not query:
            return {
                writes_to: "Error: no query provided.",
                "messages": [{"role": "system", "content": "Vector Search: empty query.", "node": "vector_search"}],
            }

        columns = [c.strip() for c in columns_raw.split(",") if c.strip()] if columns_raw else []
        if not columns:
            return {
                writes_to: "Error: no columns specified.",
                "messages": [{"role": "system", "content": "Vector Search: columns are required.", "node": "vector_search"}],
            }

        # Optional: score threshold
        score_threshold = config.get("score_threshold")
        if score_threshold is not None and score_threshold != "":
            score_threshold = float(score_threshold)
        else:
            score_threshold = None

        # Optional: dynamic filters from state (e.g. LLM-generated)
        filters_json = None
        filters_from = config.get("filters_from")
        if filters_from:
            raw_filters = resolve_state(state, filters_from)
            if raw_filters:
                if isinstance(raw_filters, dict):
                    filters_json = json.dumps(raw_filters)
                elif isinstance(raw_filters, str):
                    try:
                        json.loads(raw_filters)  # validate
                        filters_json = raw_filters
                    except json.JSONDecodeError:
                        logger.warning("Invalid filters JSON from state variable '%s': %s", filters_from, raw_filters)

        # Optional: reranker (on by default)
        enable_reranker = str(config.get("enable_reranker", "true")).lower() == "true"
        reranker = None
        if enable_reranker:
            rerank_cols_raw = config.get("columns_to_rerank", "")
            rerank_cols = [c.strip() for c in rerank_cols_raw.split(",") if c.strip()] if rerank_cols_raw else columns
            reranker = RerankerConfig(
                model="databricks_reranker",
                parameters=RerankerConfigRerankerParameters(columns_to_rerank=rerank_cols),
            )
        try:
            w = WorkspaceClient()
            response = w.vector_search_indexes.query_index(
                index_name=index_name,
                columns=columns,
                query_text=query,
                num_results=num_results,
                score_threshold=score_threshold,
                filters_json=filters_json,
                reranker=reranker,
            )
        except Exception as exc:
            logger.exception("Vector Search query failed")
            return {
                writes_to: f"Vector Search error: {exc}",
                "messages": [{"role": "system", "content": f"Vector Search error: {exc}", "node": "vector_search"}],
            }

        result_dict = response.as_dict()
        docs: list[str] = []
        data_chunk = result_dict.get("result", {}).get("data_array", [])
        col_names = [c["name"] for c in result_dict.get("manifest", {}).get("columns", [])]

        for row in data_chunk:
            row_parts = [f"{col_names[i]}: {row[i]}" for i in range(len(row)) if i < len(col_names)]
            docs.append("\n".join(row_parts))

        result_text = "\n\n---\n\n".join(docs) if docs else "(no results)"

        return {
            writes_to: result_text,
            "messages": [
                {"role": "system", "content": f"Retrieved {len(docs)} documents from '{index_name}'.\n\n{result_text}", "node": "vector_search"}
            ],
        }
